### ISSUE TITLE
Bundle client JS

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/universal-react-boilerplate#10]
Create a Bundle for client JS

**Comment by nkbt** [comment]
Webpack?

**Comment by ericelliott** [comment]
Sure.

**Comment by nkbt** [comment]
Going to do it soon, since these were done in `prod-module-boilerplate`
https://github.com/ericelliott/prod-module-boilerplate/issues/16
https://github.com/ericelliott/prod-module-boilerplate/issues/22

**Comment by ericelliott** [comment]
:+1:
