### ISSUE TITLE
Rendering System

### ISSUE THREAD

**Issue by zebulonj** [ericelliott/universal-react-boilerplate#13]
Peeling the conversation about rendering off from the broader roadmap thread (#4).

> I have purposely not baked in a template system, but I'm considering changing that, using Minimongo, Track, and Blaze to do rendering on both the server and the client. It's a bit of a moving target, though, because the Meteor project doesn't seem to have any interest in maintaining an npm version of those libs.

> Alternatively, we could show an example using React and Flux. Maybe those example implementations could be in a different repo which we link to from this one?

-- @ericelliott

**Comment by zebulonj** [comment]
@ericelliott 

>Should we be looking at trying to use JSX? Mixing markup into my JavaScript rubs me the wrong way.

> I thought it was a great idea when PHP hit the scene. We all know how that played out... It was a bad idea then, and I'm not sure that anything has changed.

I'm wrestling with the same thing. I'm coming at this from a preference for markup (any content for that matter) completely separated from logic. For that reason, I ran screaming from React.js the first few times I looked at it. However, I haven't yet seen any solution to the challenge of isomorphic rendering that I'm completely satisfied with. I have an aversion to all things Meteor, that I can't explain rationally, so I've recently started to work with React out of a desperate need for something that works.

Maybe that's a long way of saying... I'm open to a nudge in a different direction, if it comes from reason and experience that suggests a better solution.

> Also, if you're mixing markup into the JS, it seems like that puts an artificial limit targeting the output only to the DOM. IMO, one of the most attractive things about react is that it can target more than just the DOM...

Think I get what you're talking about here in the abstract, but can you provide a concrete example?

**Comment by ericelliott** [comment]
React is considering [stateless component factories](https://github.com/reactjs/react-future/blob/master/01%20-%20Core/03%20-%20Stateless%20Functions.js) that simply return JSX template literals. As long as logic is kept in different modules (as dependencies, maybe?) I don't think there's anything wrong with that. What do you think?

**Comment by ericelliott** [comment]
RE: **Targeting beyond the DOM** React is decoupled from the DOM enough that it can produce output for just about any object model. At Facebook and Netflix, they're already using those capabilities to build 100% native UIs with React, powered by JS.

That means we may be able to expand our isomorphic targeting to include multiple mobile targets as well as Node and web browsers. This is the main thing pulling me towards React right now.

**Comment by SOSANA** [comment]
1+ for react.js

**Comment by ericelliott** [comment]
On much closer inspection, React doesn't mix HTML and JS in the same way that PHP and DHTML did. In fact, it's literally a declarative shorthand notation for JS, and does not translate 1:1 with HTML. I was not completely familiar with how it worked when I wrote about it before.

I have a much different opinion now, and I'm even writing a Medium blog post defending JSX. After using it for a while, I'm wishing that standard web components were more like React / JSX. Maybe eventually they will be. ;)

**Comment by SOSANA** [comment]
@ericelliott wow! Coming from you that's impressive. Can't wait for medium post.

**Comment by ericelliott** [comment]
[JSX Looks Like an Abomination but it's Good for You](https://medium.com/javascript-scene/jsx-looks-like-an-abomination-1c1ec351a918)

**Comment by ericelliott** [comment]
@zebulonj Want to take [the react engine ticket?](https://github.com/ericelliott/universal-react-boilerplate/issues/23)

**Comment by zebulonj** [comment]
I'd be happy to.
