### ISSUE TITLE
Use ES6 and core-js with Babel

### ISSUE THREAD

**Issue by serapath** [ericelliott/universal-react-boilerplate#19]
The boilerplate uses `express`, but could use `koa` instead. Or at least `babelify` could be used as a browserify transform to already teach **some** es6 features?
* const, let
* destructuring
* default, rest, spread
* arrows
* enhanced object literals
* tail calls

**Comment by ericelliott** [comment]
I'm cool with ES6 / babelify.

KOA is not ready for wide-scale production use by virtue of the fact that it requires Node 0.11x or io.js, which both need a little more time to bake before we flock to them for prod use-cases.

I wouldn't mind that, but I'm currently using this boilerplate for production apps.

**Comment by ericelliott** [comment]
Now I've had some time to think about it, I have a good idea how to do the ES6 conversion.

See [How to Use ES6 for Isomorphic JavaScript Apps](https://medium.com/javascript-scene/how-to-use-es6-for-isomorphic-javascript-apps-2a9c3abe5ea2) for details.

**Comment by ericelliott** [comment]
@nkbt You want to tackle this?

**Comment by nkbt** [comment]
Yes, will pick it up

**Comment by ericelliott** [comment]
Nice! \o/

:clap:

**Comment by nkbt** [comment]
#34 Done

**Comment by ericelliott** [comment]
\o/
