### ISSUE TITLE
universal-react-boilerplate Gitter Chat Room

### ISSUE THREAD

**Issue by SOSANA** [ericelliott/universal-react-boilerplate#27]
@ericelliott  @nkbt @zebulonj I think we should set this up.

Thoughts?

**Comment by nkbt** [comment]
I reckon that might be necessary when `javascript-questions` becomes too busy (which is not the case yet). Maybe just add a badge to that one.

**Comment by SOSANA** [comment]
I think we should have one dedicated to this repo

**Comment by nkbt** [comment]
#28 - Having small rooms with almost no people there might not be the ideal scenario. Usually you want to split when it becomes too noisy. This is what happened with dev-ua/frontend... But until then - one room is better, cause you can get more discussion about things.
